# brew tap-new uses this file to generate an autobump workflow for the new tap
name: brew bump

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  schedule:
    # Every day at 16:25 UTC
    - cron: 25 16 * * *

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869 # 2026.08.24.1

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@a657b8b0cd35d0f65cce41fce9b24cf054b49869 # 2026.08.24.1

      - name: Bump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew bump --no-fork --open-pr --formulae --bump-synced --tap="$TAP_NAME"
