# brew tap-new uses this file to generate a bottle publish workflow for the new tap
name: brew pr-pull

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      head_sha:
        description: Expected pull request head commit SHA (optional)

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  pr-pull:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49 # 2026.08.10.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49 # 2026.08.10.2

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          HEAD_SHA: ${{ inputs.head_sha }}
          PULL_REQUEST: ${{ inputs.pull_request }}
        run: |
          if [[ -n "$HEAD_SHA" ]]
          then
            brew pr-pull --debug --tap="$GITHUB_REPOSITORY" --head-sha="$HEAD_SHA" "$PULL_REQUEST"
          else
            brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"
          fi

      - name: Push commits
        uses: Homebrew/actions/git-try-push@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49 # 2026.08.10.2
        with:
          branch: main
